package main

// EmbeddedFile represents an encrypted file embedded in the binary
type EmbeddedFile struct {
	Name            string
	EncryptedData   string
	ContentType     string
}

// EmbeddedFiles contains all encrypted files
// This map will be automatically generated by the 'add' command
var EmbeddedFiles = map[string]EmbeddedFile{
	"test.txt": {
		Name:          "test.txt",
		EncryptedData: "Y/fsXIy+EP3+jBEOVPl6wQ1t5Kmaz63nCwBWd0/QttljJIET5DV1RoDDActQLZLKODjS3vITdcvGYQcVdSgDyEkbP5ch5girTjaySgANDbcD5HAEnKYb23vOODqLm4A2K9EJRaqKFTpA34iJz8fGloOS2MA=",
		ContentType:   "text/plain; charset=utf-8",
	},
	"test.html": {
		Name:          "test.html",
		EncryptedData: "jftBcO1LOzITI2cS42JSJOtWnS53XfGBi8WYK1jPKY99Fltwtdy7KMyRjQRdxurb1H7XTjgTaQJsPFCePHVSwzzlOo1iDNFfEnDdI+RHUohDdkbHcJ/scMmqkqQ3Q9+t65TUWDyBER7AINFoRQ7TgWiy/TXpFzEVdt8YAXN9npVw51k6DimSvHRJfXskLsqPzyl3V5JXjtGTrjTp/bcWldcvEEj9PkRmA998I/vuRQwgmxVBSHj8ME9bbb4jsnTTW4jUNCNjS+oKkQiL7I8A8t6hPDpengdn0UF3mi81PaUSivWIjP7JD4iNFb7j9v0HkM03QYIGHl0=",
		ContentType:   "text/html; charset=utf-8",
	},
	"test.json": {
		Name:          "test.json",
		EncryptedData: "dUjFXkEvwcmNooAGUNJ54BMYrfO+WkUPg1Vz3eIveImlXNsnlWw4ftsmjJAv3TWjqaPnh9SGcc6rr+Z0PVKm5ClxZ5zKBZrb2Bn+dB2zckhxi/b+uR9yV4JcooLcOYoAhka+Qw/EYqXE3IvRP70xWF3B71TTapGiOIXB7GarzxBXVK+cPRO8rYnK3hXPEUIqFTOKG18=",
		ContentType:   "application/json",
	},
}
