package main

// EmbeddedFile represents an encrypted file embedded in the binary
type EmbeddedFile struct {
	Name            string
	EncryptedData   string
	ContentType     string
}

// EmbeddedFiles contains all encrypted files
// This map will be automatically generated by the 'add' command
var EmbeddedFiles = map[string]EmbeddedFile{
	"test.txt": {
		Name:          "test.txt",
		EncryptedData: "sdYbDIq1hjp0UkikUt0wDcyOWCN0ndaNJrfuRM9LLi8d29vl1M4ZBGzT2ENM5xI27OMtPAvcQgf4GV60va/b2xJZfJLIratb0u0NGXxK2yf3m0HzbO9j6SsdrN+3RtoOL45QAVvId8A0ambZjS3q0ODpmFs=",
		ContentType:   "text/plain; charset=utf-8",
	},
	"test.html": {
		Name:          "test.html",
		EncryptedData: "kO7sJOpK9mTAOL8Ig/r1QRsn3yBwB6v3W21PGJoGxb7I4Z5dxByCAK8QD+9IPBuu3NFfjWwBWWUsHVsgWOzd4jr/7Un17TtubY3AztoDnbQATfbP00jDdrH4Stutx5GubklMACzopBWcKzuiPfGgdWByO5cDBFmwvqpTzxdJkSX8D6WrZ7E+UhOTp1ts5rkMcVjfcvXspRngF0XbSY5UA8VSqIX+XHGQjxavJS6fw/LR/P7j2IieOMc4LtqGXRyYNEzvPfPqqYqdyDicDDj3DBkjMMYX8JYSdL/ss4+LjTFTuPalqjSldJcapCuSuxpCxqFwtQHvrIU=",
		ContentType:   "text/html; charset=utf-8",
	},
	"test.json": {
		Name:          "test.json",
		EncryptedData: "VlB7VUlcthnN4zG7dKxI2AeXThzqmD4bN/rd4ZVOXsfboJX5YnF+WL347MUn/DQwpVU0+s6viGFqd6eoSXX6G1iimUmgtis5yBYQYDPb39jWZ9JHC3jeToDMsz6nv6BiVcDRsLT8BcjzpqTflV2s/Zh9VJXQkqPedG1WenSNbwKptfd+h52Psn+8KQG+xS4pugL1+9A=",
		ContentType:   "application/json",
	},
}
